// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdeRNOjG2sv44IP7Xyp_DlFw11B3zRpbk',
    appId: '1:308028823623:web:d033ac488fba81265a7962',
    messagingSenderId: '308028823623',
    projectId: 'app-reunioes',
    authDomain: 'app-reunioes.firebaseapp.com',
    storageBucket: 'app-reunioes.appspot.com',
    measurementId: 'G-CFZCSB6Y5X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcDJnZxD1UTJFW2voc6hqvEJXP2dFYOPo',
    appId: '1:308028823623:android:bceeeb690b9433fb5a7962',
    messagingSenderId: '308028823623',
    projectId: 'app-reunioes',
    storageBucket: 'app-reunioes.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKmyufyw-FbOikVoiOWfHs--iMOdNc908',
    appId: '1:308028823623:ios:dc22133f80a4c5b65a7962',
    messagingSenderId: '308028823623',
    projectId: 'app-reunioes',
    storageBucket: 'app-reunioes.appspot.com',
    iosClientId: '308028823623-sv6cbrapbdieg4vfcok0qjre4i6992fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.reunioes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKmyufyw-FbOikVoiOWfHs--iMOdNc908',
    appId: '1:308028823623:ios:b0461986a85a93605a7962',
    messagingSenderId: '308028823623',
    projectId: 'app-reunioes',
    storageBucket: 'app-reunioes.appspot.com',
    iosClientId: '308028823623-fns2aitoqq5ica118pk5vp0s6u6suho3.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
